"use client";

import React, { useEffect, useState } from "react";
import { useToast } from "@/context/ToastContext";

interface AffiliateData {
  referralCode: string;
  referralLink: string;
  totalReferrals: number;
  activeReferrals: number;
  totalEarnedUsdc: number;
  referrees: Array<{
    id: string;
    username: string;
    joinedAt: string;
  }>;
}

export default function AffiliateDashboardPage() {
  const { toast } = useToast();
  const [data, setData] = useState<AffiliateData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const fetchAffiliateData = async () => {
      try {
        setLoading(true);
        const token = localStorage.getItem("token");
        const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";

        const res = await fetch(`${apiUrl}/api/v1/financial/affiliate-dashboard`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        if (!res.ok) throw new Error("Failed to fetch affiliate dashboard data");
        const json = await res.json();
        setData(json.data);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : "An error occurred";
        setError(msg);
        toast.error(msg);
      } finally {
        setLoading(false);
      }
    };

    fetchAffiliateData();
  }, [toast]);

  const handleCopy = () => {
    if (data?.referralLink) {
      navigator.clipboard.writeText(data.referralLink);
      setCopied(true);
      toast.success("Affiliate referral link copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 p-6 md:p-12">
      <div className="max-w-6xl mx-auto space-y-8">
        <header className="border-b border-slate-800 pb-6">
          <h1 className="text-3xl font-bold text-white tracking-tight">
            Affiliate & Referral Rewards Dashboard
          </h1>
          <p className="text-slate-400 mt-1">
            Invite friends to paid leagues and automatically earn 20% of the platform fees generated by your referrals with on-chain settlement.
          </p>
        </header>

        {loading && (
          <div className="flex justify-center items-center py-20 text-slate-400">
            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-emerald-500 mr-3"></div>
            Loading affiliate program details...
          </div>
        )}

        {error && (
          <div className="bg-red-950/50 border border-red-800 text-red-300 p-4 rounded-lg">
            Error loading affiliate data: {error}
          </div>
        )}

        {!loading && !error && data && (
          <div className="space-y-8">
            {/* Referral Link Share Box */}
            <section className="bg-slate-800/80 p-6 rounded-xl border border-slate-700/80 space-y-4">
              <h2 className="text-lg font-semibold text-white">Your Unique Referral Link</h2>
              <div className="flex flex-col sm:flex-row gap-3">
                <input
                  type="text"
                  readOnly
                  value={data.referralLink}
                  className="flex-1 bg-slate-900 border border-slate-700 text-emerald-400 font-mono text-sm px-4 py-2.5 rounded-lg focus:outline-none focus:border-emerald-500"
                />
                <button
                  onClick={handleCopy}
                  className="bg-emerald-600 hover:bg-emerald-500 text-white font-medium px-6 py-2.5 rounded-lg transition flex items-center justify-center gap-2"
                >
                  {copied ? "Copied! ✓" : "Copy Link 📋"}
                </button>
              </div>
              <p className="text-xs text-slate-400">
                Share this link with your friends. Code: <span className="font-mono text-white">{data.referralCode}</span>
              </p>
            </section>

            {/* Metrics Overview Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-slate-800/60 p-6 rounded-xl border border-slate-700/60">
                <span className="text-sm font-medium text-slate-400">Total Referrals</span>
                <div className="text-3xl font-bold text-white mt-2 font-mono">{data.totalReferrals}</div>
              </div>
              <div className="bg-slate-800/60 p-6 rounded-xl border border-slate-700/60">
                <span className="text-sm font-medium text-slate-400">Active Paid Participants</span>
                <div className="text-3xl font-bold text-sky-400 mt-2 font-mono">{data.activeReferrals}</div>
              </div>
              <div className="bg-slate-800/60 p-6 rounded-xl border border-slate-700/60">
                <span className="text-sm font-medium text-slate-400">Total Earned Rewards</span>
                <div className="text-3xl font-bold text-emerald-400 mt-2 font-mono">${data.totalEarnedUsdc.toFixed(2)} USDC</div>
              </div>
            </div>

            {/* Referred Users Table */}
            <section className="bg-slate-800/60 p-6 rounded-xl border border-slate-700/60 space-y-4">
              <h2 className="text-lg font-semibold text-white">Referred Users</h2>
              {data.referrees.length === 0 ? (
                <p className="text-slate-400 text-sm py-4">No user referrals recorded yet. Copy and share your link above to get started!</p>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-sm text-slate-300">
                    <thead className="text-xs uppercase bg-slate-900/80 text-slate-400 border-b border-slate-700">
                      <tr>
                        <th className="py-3 px-4">User</th>
                        <th className="py-3 px-4 text-right">Joined Date</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60">
                      {data.referrees.map((ref) => (
                        <tr key={ref.id} className="hover:bg-slate-800/40">
                          <td className="py-3 px-4 font-medium text-white">{ref.username}</td>
                          <td className="py-3 px-4 text-right text-slate-400 font-mono">
                            {new Date(ref.joinedAt).toLocaleDateString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </section>
          </div>
        )}
      </div>
    </div>
  );
}
